openapi: 3.0.3
info:
  title: MoEngage Content Block API
  version: '1.0'
  description: API for creating, updating, and searching reusable Content Blocks within the MoEngage platform.
tags:
  - name: Content Blocks
    description: Operations to manage reusable content blocks for campaigns.
servers:
  - url: 'https://api-0{dc}.moengage.com/v1/external/campaigns'
    description: MoEngage Content Blocks API Server
    variables:
      dc:
        default: '1'
        description: 'Your MoEngage Data Center (DC). Can be 1, 2, 3, etc.'
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
security:
  - moeAppKey: []

paths:
  /content-blocks:
    post:
      tags:
        - Content Blocks
      summary: Create Content Block
      description: Creates a new content block that can be reused in campaigns.
      requestBody:
        required: true
        description: The details of the content block to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContentBlockRequest'
            example:
              name: "Summer_Sale_Header"
              label: "summer_sale_header_2025"
              description": "Header for all summer sale communications"
              content_type": "HTML"
              raw_content": "<h1>Huge Summer Sale!</h1>"
              images_used": []
              status": "ACTIVE"
              created_by": "marketing@example.com"
              content_block_used" : []
      responses:
        '202':
          description: Accepted. The request has been accepted for processing.
        '400':
          description: Bad Request. The request is invalid due to missing or incorrect data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Content Blocks
      summary: Update Content Block
      description: Updates an existing content block.
      requestBody:
        required: true
        description: The updated details for the content block.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContentBlockRequest'
            example:
              id: "634fdf4db9c206ba55b8223b"
              raw_content": "<h1>Massive Summer Sale!</h1>"
              updated_by": "jane.doe@example.com"
      responses:
        '202':
          description: Accepted. The update request has been accepted for processing.
        '400':
          description: Bad Request. Invalid ID or other validation errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /content-blocks/get-by-ids:
    post:
      tags:
        - Content Blocks
      summary: Get Specific Content Blocks
      description: Fetches one or more content blocks by their unique IDs.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetByIdsRequest'
      responses:
        '202':
          description: Accepted. Returns the requested content blocks in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentBlockListResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /content-blocks/search:
    post:
      tags:
        - Content Blocks
      summary: Search Content Blocks
      description: Searches for content blocks based on specified filter criteria.
      requestBody:
        required: true
        description: A set of filters to apply to the search. Sending an empty filters object will return all content blocks.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchContentBlockRequest'
      responses:
        '202':
          description: Accepted. Returns the matching content blocks in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentBlockListResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    moeAppKey:
      type: apiKey
      in: header
      name: MOE-APPKEY
      description: Your MoEngage Workspace ID (also referred to as App Key).

  schemas:
    ErrorResponse:
      type: object
      properties:
        title:
          type: string
          example: "Invalid Field Value"
        description:
          type: string
          example: "app_key - Some of the field values are invalid: app_key : None"
        code:
          type: string
          example: "nGpUNpDQ"

    CreateContentBlockRequest:
      type: object
      required:
        - name
        - label
        - raw_content
        - content_type
        - created_by
      properties:
        name:
          type: string
          description: Name of the content block.
        label:
          type: string
          description: A unique label to identify the content block.
        status:
          type: string
          enum: [ACTIVE, DRAFT]
          description: Status of the content block.
        raw_content:
          type: string
          description: The raw HTML or Text content of the block.
        content_type:
          type: string
          enum: [HTML, TEXT]
          description: The type of content.
        description:
          type: string
          description: An optional description for the content block.
        created_by:
          type: string
          format: email
          description: Email ID of the user creating the content block.
        tag_ids:
          type: array
          items:
            type: string
          description: List of tag IDs to associate with the content block.
        team_ids:
          type: array
          items:
            type: string
          description: List of team IDs that can access this block.
        content_block_used:
          type: array
          items:
            type: string
          description: List of other content block names nested within this block.
        images_used:
          type: array
          items:
            type: string
            format: uri
          description: List of image URLs used in the content block.

    UpdateContentBlockRequest:
      type: object
      required:
        - id
        - raw_content
        - updated_by
      properties:
        id:
          type: string
          description: The unique ID of the content block to update.
        name:
          type: string
          description: A new name for the content block.
        status:
          type: string
          enum: [ACTIVE, DRAFT]
          description: The new status of the content block.
        raw_content:
          type: string
          description: The new raw HTML or Text content for the block.
        description:
          type: string
          description: A new description for the content block.
        updated_by:
          type: string
          format: email
          description: Email ID of the user updating the content block.
        tag_ids:
          type: array
          items:
            type: string
          description: A new list of tag IDs to associate with the content block.
        team_ids:
          type: array
          items:
            type: string
          description: A new list of team IDs that can access this block.
        content_block_used:
          type: array
          items:
            type: string
          description: A new list of other content block names nested within this block.
        images_used:
          type: array
          items:
            type: string
            format: uri
          description: A new list of image URLs used in the content block.

    GetByIdsRequest:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: string
          description: A list of content block IDs to retrieve.
        is_raw_content_required:
          type: boolean
          description: If true, the `raw_content` field will be included in the response.
          default: false

    SearchContentBlockRequest:
      type: object
      properties:
        filters:
          type: object
          properties:
            content_type:
              type: array
              items:
                type: string
                enum: [HTML, TEXT]
            team_ids:
              type: array
              items:
                type: string
            tag_ids:
              type: array
              items:
                type: string
            status:
              type: array
              items:
                type: string
                enum: [ACTIVE, ARCHIVED]
            updated_by:
              type: array
              items:
                type: string
                format: email
            search_text:
              type: string
              description: Search term to match against content block names.

    ContentBlockObject:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        label: { type: string }
        description: { type: string }
        content_type: { type: string, enum: [HTML, TEXT] }
        content: { type: string, description: "Rendered content of the block." }
        raw_content: { type: string, description: "Raw content provided during creation/update." }
        status: { type: string, enum: [ACTIVE, DRAFT, ARCHIVED] }
        created_by: { type: string, format: email }
        created_at: { type: string, format: date-time }
        updated_by: { type: string, format: email }
        updated_at: { type: string, format: date-time }
        tag_ids: { type: array, items: { type: string } }
        team_ids: { type: array, items: { type: string } }
        images_used: { type: array, items: { type: string, format: uri } }

    ContentBlockListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ContentBlockObject'