openapi: 3.0.3
info:
  title: MoEngage Email Template API
  version: '2.0'
  description: API for creating, updating, and searching Email templates within the MoEngage platform. Templates created via this API are compatible with the Custom HTML Editor.
tags:
  - name: Email Templates
    description: Operations to manage email templates.
servers:
  - url: 'https://api-{dc}.moengage.com/v2'
    description: MoEngage Email Template API Server
    variables:
      dc:
        default: '01'
        description: 'Your MoEngage Data Center (DC). Can be 01, 02, 03, etc.'
        enum:
          - '01'
          - '02'
          - '03'
          - '04'
security:
  - basicAuth: []
  - moeAppKey: []

paths:
  /email-templates:
    post:
      tags:
        - Email Templates
      summary: Create Email Template
      description: Creates a new email template in MoEngage.
      requestBody:
        required: true
        description: The details of the email template to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailTemplatePayload'
            example:
              name: "End_Of_Season_Sale_Template"
              html": "<!DOCTYPE html><html><body><p>Your Email Template Content Here</p></body></html>"
              subject": "End of Season Sale!"
              attachments": ["https://app-cdn.moengage.com/assets/LogoThumbnail.jpg"]
              sender_name": "Your Brand Name"
              source": "Partner"
              updated_by": "john.doe@example.com"
      responses:
        '200':
          description: Request processed. The status indicates success or failure.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CreateUpdateSuccessResponse'
                  - $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication Failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit breached.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - Email Templates
      summary: Get All Email Templates
      description: Fetches a paginated list of all email templates available in your MoEngage account.
      parameters:
        - name: page
          in: query
          required: true
          description: The page number to fetch. Each page returns up to 20 templates.
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Successfully retrieved the list of templates.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllTemplatesResponse'
        '401':
          description: Authentication Failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /email-templates/{template_id}:
    get:
      tags:
        - Email Templates
      summary: Get a Specific Email Template
      description: Fetches the details of a single email template using its unique template ID.
      parameters:
        - name: template_id
          in: path
          required: true
          description: The unique identifier of the template, generated upon creation.
          schema:
            type: string
            example: "63f30792c66ddcaac2ef9109"
      responses:
        '200':
          description: Successfully retrieved the template details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSpecificTemplateResponse'
        '400':
          description: Bad Request, likely due to an invalid template ID format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication Failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Email Templates
      summary: Update a Specific Email Template
      description: Updates an existing email template by specifying its template ID.
      parameters:
        - name: template_id
          in: path
          required: true
          description: The unique identifier of the template to update.
          schema:
            type: string
            example: "63f30792c66ddcaac2ef9109"
      requestBody:
        required: true
        description: The updated details for the email template.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailTemplatePayload'
      responses:
        '200':
          description: Template updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUpdateSuccessResponse'
        '400':
          description: Bad Request. Invalid template ID or other validation errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /bulk/email-templates:
    put:
      tags:
        - Email Templates
      summary: Bulk Create or Update Email Templates
      description: Creates or updates up to 50 email templates in a single request. An object with an `id` field will be treated as an update, otherwise it will be a create.
      requestBody:
        required: true
        description: An array of up to 50 email template objects.
        content:
          application/json:
            schema:
              type: array
              maxItems: 50
              items:
                $ref: '#/components/schemas/BulkTemplateObject'
            example:
              - name: "New_Bulk_Template"
                html: "<html><body><p>New content</p></body></html>"
                source: "Bulk API"
              - id: "645a2bd910e0307e6d7f7717"
                name: "Updated_Coupon_Template"
                html": "<html><body><p>Updated content</p></body></html>"
                source": "Bulk API"
                updated_by": "jane.doe@example.com"
      responses:
        '200':
          description: Bulk request processed. The response body details which templates were created and updated, and which failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkResponse'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication Failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic Authentication using Workspace ID as username and Data API Key as password.
    moeAppKey:
      type: apiKey
      in: header
      name: MOE-APPKEY
      description: Your MoEngage Workspace ID.

  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        data:
          type: object
          properties:
            code:
              type: integer
              example: 400
            title:
              type: string
              example: Invalid request body
            description:
              type: string
              example: MOE-APPKEY header is invalid or empty

    EmailTemplatePayload:
      type: object
      required:
        - name
        - html
        - source
      properties:
        name:
          type: string
          minLength: 5
          maxLength: 50
          pattern: '^[a-zA-Z0-9_ ]*$'
          description: The name for the template. Alphanumeric and underscores only.
        html:
          type: string
          description: The full HTML content of the email. Must include `<html>` and `<body>` tags.
        subject:
          type: string
          description: The subject line for the email.
        attachments:
          type: array
          maxItems: 10
          items:
            type: string
            format: uri
          description: A list of public URLs for attachments. Total size should be less than 20MB.
        sender_name:
          type: string
          description: The 'From' name displayed to the recipient.
        source:
          type: string
          description: The source of the template creation, e.g., the name of your internal tool or partner.
        updated_by:
          type: string
          description: Identifier (e.g., email) of the user creating or updating the template.

    BulkTemplateObject:
      allOf:
        - $ref: '#/components/schemas/EmailTemplatePayload'
        - type: object
          properties:
            id:
              type: string
              description: If provided, this template will be updated. If omitted, a new template will be created.

    CreateUpdateSuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: object
          properties:
            id:
              type: string
              description: The unique ID of the created/updated template.
              example: "63f4962d4d31f4c68d980a01"
            msg:
              type: string
              example: "Custom email template saved"

    GetAllTemplatesResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: object
          properties:
            templates:
              type: array
              items:
                type: object
                properties:
                  template_id: { type: string }
                  template_name: { type: string }
                  is_archived: { type: boolean }
                  builder_supported: { type: boolean, default: false }
                  editor: { type: string, example: "Froala Editor" }
                  created_date: { type: string, format: "date-time" }
                  updated_at: { type: string, format: "date-time" }
                  updated_by: { type: string }
            no_of_templates:
              type: integer

    GetSpecificTemplateResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        template_id:
          type: string
        template_name:
          type: string
        subject:
          type: string
        template_content:
          type: string
          description: The HTML content of the template.
        attachments:
          type: array
          items:
            type: object
            properties:
              id: { type: string }
              name: { type: string, format: uri }
              type: { type: string, example: "link" }
              fileType: { type: string, example: "URL" }
              url: { type: string, format: uri }
        source:
          type: string
        sender_name:
          type: string
        editor:
          type: string
        created_date:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        updated_by:
          type: string

    BulkResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: object
          properties:
            new_templates:
              type: array
              items:
                type: string
              description: A list of IDs for newly created templates or error messages for failed creations.
            updated_templates:
              type: array
              items:
                type: string
              description: A list of IDs for successfully updated templates or error messages for failed updates.