openapi: 3.0.3
info:
  title: MoEngage GDPR / CCPA API
  description: API to create or update user rights for GDPR / CCPA compliance, including erasing personal data.
  version: '1.0'
servers:
  - url: 'https://api-0{X}.moengage.com/v1'
    description: MoEngage API Server
    variables:
      X:
        default: '1'
        description: 'Your MoEngage Data Center (DC) number. Refer to MoEngage docs for your correct DC.'
tags:
  - name: GDPR
    description: Manage GDPR and CCPA data requests.
security:
  - basicAuth: []
paths:
  /opengdpr_requests/{Workspace_ID}:
    post:
      tags:
        - GDPR
      summary: Submit GDPR/CCPA Request
      description: 'Ensures all the rights of users are created or updated for GDPR / CCPA compliance. You can erase the personal data of specific users as defined under GDPR using this API.'
      operationId: submitGdprRequest
      parameters:
        - name: Workspace_ID
          in: path
          required: true
          schema:
            type: string
          description: 'The Workspace ID for your MoEngage account, available on the MoEngage Dashboard.'
          example: 'YOUR_WORKSPACE_ID_XXXX'
        - name: MOE-APPKEY
          in: header
          required: true
          schema:
            type: string
          description: 'This is the workspace ID (earlier APP ID) of your MoEngage workspace.'
          example: 'YOUR_WORKSPACE_ID_XXXX'
      requestBody:
        description: The GDPR/CCPA request. Max payload size is 100kb.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GdprRequest'
            example:
              request_type: erasure
              submitted_time: '2018-10-05T15:00:00Z'
              identities:
                - identity_type: email
                  identity_value: johndoe@example.com
              api_version: '1.0'
      responses:
        '200':
          description: Your request has been accepted and will be processed soon.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GdprSuccessResponse'
              example:
                status: success
                message: Your request has been accepted and will be processed soon.
                request_id: 'a7551968-d5d6-44b2-9831-815ac9017798'
        '400':
          description: Bad Request. (e.g., malformed JSON, missing required fields).
        '401':
          description: Authentication Failure.
        '413':
          description: 'Payload Too Large. The request payload exceeds the 100kb limit.'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: 'Basic Authentication using Workspace ID (username) and Data API Key (password) from MoEngage Dashboard > Settings > Account > APIs.'
  schemas:
    GdprRequest:
      type: object
      required:
        - request_type
        - submitted_time
        - identities
        - api_version
      properties:
        request_type:
          type: string
          description: This is used to request for GDPR details or request to erase the GDPR details.
          example: erasure
        submitted_time:
          type: string
          format: date-time
          description: This identifies the time when the request was sent (ISO 8601 format).
          example: '2018-10-05T15:00:00Z'
        identities:
          type: array
          description: This provides the details of the user such as email address, phone number, and so on.
          items:
            $ref: '#/components/schemas/UserIdentity'
        api_version:
          type: string
          description: This identifies the API version used to send the GDPR request.
          example: '1.0'
    UserIdentity:
      type: object
      properties:
        identity_type:
          type: string
          description: The type of user identifier.
          enum:
            - id
            - user_secondary_id
            - email
            - mobile
            - google_advertising_id
            - advertising_identifier
          example: email
        identity_value:
          type: string
          description: The value for the specified user identifier.
          example: johndoe@example.com
    GdprSuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Your request has been accepted and will be processed soon.
        request_id:
          type: string
          format: uuid
          example: 'a7551968-d5d6-44b2-9831-815ac9017798'