openapi: 3.0.3
info:
  title: Global Throttling
  version: 1.0.7
  contact: {}
servers:
  - url: https://api.yourdomain.com # 👈 Please replace with your actual API base URL
paths:
  /v1/campaigns/core/throttling/settings:
    post:
      summary: Create throttling settings for service
      description: Create throttling settings
      operationId: createThrottlingSettingsApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - unique_identifier_key
                - unique_identifier_value
              properties:
                unique_identifier_key:
                  type: string
                  example: "DB_NAME"
                unique_identifier_value:
                  type: string
                  example: "DemoApp"
                throttling_limit:
                  type: object
                  properties:
                    service_name:
                      type: integer
                      example: 1000
            examples:
              Create throttling settings:
                value:
                  unique_identifier_key: "DB_NAME"
                  unique_identifier_value: "DemoApp"
                  throttling_limit:
                    PUSH:
                      is_enabled: true
                      limit: 1000
                      min_limit: 3
                      max_limit: 55000
                    PUSH_ANDROID:
                      is_enabled: false
                      limit: 1000
                      min_limit: 3
                      max_limit: 55000
                    SMS:
                      is_enabled: true
                      limit: 1000
                      min_limit: 3
                      max_limit: 55000
                    EMAIL:
                      is_enabled: true
                      limit: 10000
                      min_limit: 3
                      max_limit: 55000
      responses:
        '201':
          description: "Success Response"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
    put:
      summary: Edit throttling settings for service
      description: Edit throttling settings
      operationId: editThrottlingSettingsApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - unique_identifier_key
                - unique_identifier_value
              properties:
                unique_identifier_key:
                  type: string
                  example: "DB_NAME"
                unique_identifier_value:
                  type: string
                  example: "DemoApp"
                throttling_limit:
                  type: object
                  properties:
                    service_name:
                      type: integer
                      example: 1000
            examples:
              Edit throttling settings:
                value:
                  unique_identifier_key: "DB_NAME"
                  unique_identifier_value: "DemoApp"
                  throttling_limit:
                    PUSH:
                      is_enabled: true
                      limit: 1000
                      min_limit: 3
                      max_limit: 55000
                    EMAIL:
                      is_enabled: true
                      limit: 9000
                      min_limit: 5
                      max_limit: 50000
      responses:
        '204':
          description: "Success Response"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
    get:
      summary: "Get Throttling settings for service"
      description: "Get Throttling settings"
      responses:
        '200':
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignThrottlingApiResponse"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
  /v1/campaigns/core/throttling/meta:
    post:
      summary: Create throttling meta for service
      description: Create throttling Meta
      operationId: createThrottlingMetaApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant
                - service
                - status
              properties:
                tenant:
                  type: string
                  example: "Journey"
                service:
                  type: string
                  example: "PUSH"
                priority:
                  type: integer
                  example: 0
                status:
                  type: string
                  example: "NOT_SENT"
                entity_id:
                  type: string
                  example: "entity123"
                entity_created_time:
                  type: string
                  format: date-time
                  example: "2025-09-22T12:00:00Z"
                entity_level_throttling:
                  type: integer
                  example: 1000
                throttling_services_applicable:
                  type: array
                  items:
                    type: string
                  example: ['PUSH', 'SMS']
            examples:
              Create throttling Meta:
                value:
                  tenant: "Journey"
                  service: "PUSH"
                  priority: 0
                  status: "NOT_SENT"
                  entity_id: "cid"
                  entity_created_time: "2025-09-22T12:00:00Z"
                  entity_level_throttling: 100
                  throttling_services_applicable: ['PUSH', 'SMS']
      responses:
        '201':
          description: "Success Response"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
    put:
      summary: Edit throttling Meta for service
      description: Edit throttling Meta
      operationId: editThrottlingMetaApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tenant:
                  type: string
                  example: "DemoApp"
                priority:
                  type: integer
                  example: 0
                entity_id:
                  type: string
                  example: "entity123"
                entity_level_throttling:
                  type: integer
                  example: 100
                status:
                  type: string
                  example: "QUEUED"
            examples:
              Edit throttling Meta:
                value:
                  tenant: "DemoApp"
                  priority: 1
                  entity_id: "cid"
                  status: "QUEUED"
                  entity_level_throttling: 100
      responses:
        '204':
          description: "Success Response"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
  /v1/campaigns/core/throttling/meta/search:
    post:
      summary: Get throttling meta for service
      description: Search throttling Meta
      operationId: searchThrottlingMetaApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant
                - service
                - status
              properties:
                tenant:
                  type: string
                  example: "Journey"
                service:
                  type: string
                  example: "PUSH"
                status:
                  type: string
                  example: "NOT_SENT"
                entity_id:
                  type: string
                  example: "entity123"
            examples:
              Search throttling Meta:
                value:
                  tenant: "Journey"
                  service: "PUSH"
                  status: "NOT_SENT"
                  entity_id: "cid"
      responses:
        '201':
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignThrottlingMetaApiResponse"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
  /v1/campaigns/core/throttling/batch:
    post:
      summary: Create throttling Batch for service
      description: Create throttling Batch
      operationId: createThrottlingBatchApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - tenant
                - entity_id
                - batch_entities
                - queue
                - task_name
                - task_args
              properties:
                status:
                  type: string
                  example: "QUEUED"
                batch_status:
                  type: integer
                  example: 0
                tenant:
                  type: string
                  example: "DemoApp"
                entity_id:
                  type: string
                  example: "cid"
                batch_entities:
                  type: array
                  items:
                    type: string
                  example: ["entity1", "entity2"]
                params:
                  type: object
                  properties:
                    batch_no:
                      type: integer
                      example: 1
                queue:
                  type: string
                  example: "high_priority_queue"
                task_name:
                  type: string
                  example: "process_batch_task"
                task_args:
                  type: array
                  items:
                    type: string
                  example: ["arg1", "arg2"]
            examples:
              Create throttling Batch:
                value:
                  status: "QUEUED"
                  batch_status: 0
                  tenant: "DemoApp"
                  entity_id: "cid"
                  batch_entities: ["user1", "user2"]
                  params:
                    batch_no: 1
                  queue: "default_queue"
                  task_name: "process_batch"
                  task_args: ['arg_value']
      responses:
        '201':
          description: "Success Response"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
    put:
      summary: Edit throttling Batch for service
      description: Edit throttling Batch
      operationId: editThrottlingBatchApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - tenant
                - entity_id
              properties:
                status:
                  type: string
                  example: "PROCESSING"
                batch_status:
                  type: integer
                  example: 1
                tenant:
                  type: string
                  example: "DemoApp"
                entity_id:
                  type: string
                  example: "cid"
                retry_count:
                  type: integer
                  example: 0
            examples:
              Edit throttling Batch:
                value:
                  status: "PROCESSING"
                  batch_status: 1
                  tenant: "DemoApp"
                  entity_id: "cid"
                  retry_count: 1
      responses:
        '204':
          description: "Success Response"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
  /v1/campaigns/core/throttling/batch/search:
    post:
      summary: Search throttling Batch for service
      description: Search throttling Batch
      operationId: searchThrottlingBatchApi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - tenant
                - entity_id
              properties:
                status:
                  type: string
                  example: "QUEUED"
                tenant:
                  type: string
                  example: "DemoApp"
                entity_id:
                  type: string
                  example: "cid"
            examples:
              Search throttling Batch:
                value:
                  status: "QUEUED"
                  tenant: "DemoApp"
                  entity_id: "cid"
      responses:
        '201':
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignThrottlingBatchApiResponse"
        '400':
          description: "Bad Request Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
        '500':
          description: "Internal Server Error Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorApiResponse"
      security:
        - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    ErrorApiResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: "string"
            message:
              type: "string"
            target:
              type: "string"
            details:
              type: array
              items:
                type: object
                properties:
                  message:
                    type: "string"
                  target:
                    type: "string"
    CampaignThrottlingApiResponse:
      type: object
      properties:
        throttling_limit:
          type: object
          properties:
            PUSH:
              type: object
              properties:
                is_enabled:
                  type: boolean
                limit:
                  type: integer
                min_limit:
                  type: integer
                max_limit:
                  type: integer
            SMS:
              type: object
              properties:
                is_enabled:
                  type: boolean
                limit:
                  type: integer
                min_limit:
                  type: integer
                max_limit:
                  type: integer
            EMAIL:
              type: object
              properties:
                is_enabled:
                  type: boolean
                limit:
                  type: integer
                min_limit:
                  type: integer
                max_limit:
                  type: integer
        unique_identifier_key:
          type: "string"
        unique_identifier_value:
          type: "string"
    CampaignThrottlingMetaApiResponse:
      type: object
      properties:
        tenant:
          type: "string"
        service:
          type: "string"
        priority:
          type: "integer"
        status:
          type: "string"
        entity_id:
          type: "string"
        entity_created_time:
          type: "string"
          format: "date-time"
        entity_level_throttling:
          type: "integer"
        throttling_services_applicable:
          type: array
          items:
            type: "string"
    CampaignThrottlingBatchApiResponse:
      type: object
      properties:
        status:
          type: string
        batch_status:
          type: integer
        tenant:
          type: string
        entity_id:
          type: string
        batch_entities:
          type: array
          items:
            type: string
        params:
          type: object
          properties:
            batch_no:
              type: integer
        queue:
          type: string
        task_name:
          type: string
        task_args:
          type: array
          items:
            type: string
        retry_count:
          type: integer


