openapi: 3.0.3
info:
  title: MoEngage Inform API
  version: '1.0'
  description: |-
    API for MoEngage Inform, a unified messaging infrastructure for building and managing transactional alerts across multiple channels like SMS, Email, and Push.
tags:
  - name: Transactional Alerts
    description: Send transactional alerts using pre-configured templates.
servers:
  - url: 'https://api-0{dc}.moengage.com/v1.0'
    description: Live Alerts Endpoint
    variables:
      dc:
        default: '1'
        description: 'Your MoEngage Data Center (DC). Can be 1, 2, 3, etc.'
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
  - url: 'https://sandbox-api-0{dc}.moengage.com/v1.0'
    description: Test/Sandbox Alerts Endpoint
    variables:
      dc:
        default: '1'
        description: 'Your MoEngage Data Center (DC). Can be 1, 2, 3, etc.'
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
paths:
  /alerts/send:
    post:
      tags:
        - Transactional Alerts
      summary: Send Transactional Alert
      description: Sends a transactional alert to a user on one or more channels using a pre-configured Alert ID or Alert Reference Name. Use the Live endpoint for production and the Test/Sandbox endpoint for testing.
      security:
        - basicAuth: []
          moeAppKey: []
      requestBody:
        required: true
        description: The payload containing the alert identifier, transaction details, and recipient information for each channel.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformRequest'
            examples:
              multiChannelWithPersonalization:
                summary: Multi-Channel with Personalization
                value:
                  alert_id": "636b77e6e2cf83277195fb60"
                  alert_reference_name": "Demo_ID"
                  user_id": "USER_12345"
                  transaction_id": "TXN_987654321"
                  payloads":
                    PUSH":
                      recipient": "<push-token>"
                      personalized_attributes":
                        firstname": "John"
                        orderid": "ORD_554433"
                    EMAIL":
                      recipient": "john.doe@moengage.com"
                      personalized_attributes":
                        firstname": "John"
                        orderid": "ORD_554433"
              singleChannelNoPersonalization:
                summary: Single Channel (SMS) without Personalization
                value:
                  alert_id": "636b77e6e2cf83277195fb60"
                  alert_reference_name": "Demo_ID"
                  user_id": "USER_12345"
                  transaction_id": "TXN_ABCDEF123"
                  payloads":
                    SMS":
                      recipient": "1234567890"
      responses:
        '200':
          description: Request has been received and processed. The response body contains the status for the overall request and for each individual channel, which may include channel-specific errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformSuccessResponse'
        '400':
          description: Bad Request. Invalid payload format, incorrect JSON, invalid or missing Alert ID, or invalid channel configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformErrorResponse'
        '401':
          description: Unauthorized. Invalid authentication credentials (App Key, Basic Auth, or API Secret).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformErrorResponse'
        '409':
          description: Duplicate Request. A request with the same `transaction_id` was received within the last 5 minutes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformErrorResponse'
        '429':
          description: Rate Limit Reached. The number of requests per minute has exceeded the allowed limit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformErrorResponse'
        '500':
          description: Internal Server Error. An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformErrorResponse'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic Authentication using Workspace ID as username and Inform API Key as password.
    moeAppKey:
      type: apiKey
      in: header
      name: MOE-APPKEY
      description: Your MoEngage Workspace ID.

  schemas:
    PayloadChannel:
      type: object
      required:
        - recipient
      properties:
        recipient:
          type: string
          description: 'The target for the notification. This should be a mobile number for SMS, an email address for EMAIL, or a push token for PUSH.'
        personalized_attributes:
          type: object
          additionalProperties: true
          description: A key-value map of attributes for personalizing the message template.
        sender_attributes:
          type: array
          items:
            type: string
          description: A list of API attributes for evaluating which sender to use.
        personalized_attachments:
          type: object
          additionalProperties:
            type: string
            format: byte
            description: 'A map where keys are attachment identifiers (defined in the template) and values are Base64-encoded strings of the attachment content.'

    InformRequest:
      type: object
      required:
        - transaction_id
        - payloads
      properties:
        alert_id:
          type: string
          description: The unique ID of the Live or Test Alert. Either this or `alert_reference_name` is mandatory.
        alert_reference_name:
          type: string
          description: The reference name for the Alert. Can be used as an alternative to `alert_id`.
        user_id:
          type: string
          description: Optional unique user identifier to map channel events back to a user profile in MoEngage.
        transaction_id:
          type: string
          maxLength: 50
          description: A unique identifier for the transaction to support idempotency. Duplicate requests with the same ID within 5 minutes will be rejected.
        payloads:
          type: object
          description: An object where keys are the channel names (SMS, EMAIL, PUSH) and values contain the recipient and personalization data. At least one channel is required.
          properties:
            SMS:
              $ref: '#/components/schemas/PayloadChannel'
            EMAIL:
              $ref: '#/components/schemas/PayloadChannel'
            PUSH:
              $ref: '#/components/schemas/PayloadChannel'

    ChannelStatus:
      type: object
      properties:
        message:
          type: string
        err_code:
          type: string
        status_code:
          type: integer

    InformSuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Successfully Received"
        request_id:
          type: string
        SMS:
          $ref: '#/components/schemas/ChannelStatus'
        EMAIL:
          $ref: '#/components/schemas/ChannelStatus'
        PUSH:
          $ref: '#/components/schemas/ChannelStatus'

    InformErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Invalid Alert ID"
        err_code:
          type: string
          example: "BAD_REQUEST"
        status_code:
          type: integer
          example: 120002