openapi: 3.0.3
info:
  title: MoEngage Broadcast Live Activities API
  version: '1.0'
  description: API for starting, updating, and ending broadcast Live Activities for iOS Push Campaigns. Live Activities must be created via the Create Push Campaigns API with the `BROADCAST_LIVE_ACTIVITY` delivery type.
tags:
  - name: Live Activities
    description: Operations to manage broadcast Live Activities for iOS.
servers:
  - url: 'https://api-0{dc}.moengage.com/v1.0'
    description: Live Activities API Server
    variables:
      dc:
        default: '1'
        description: 'Your MoEngage Data Center (DC). Can be 1, 2, 3, etc.'
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
  - url: 'https://sandbox-api-0{dc}.moengage.com/v1.0'
    description: Test/Sandbox Live Activities API Server
    variables:
      dc:
        default: '1'
        description: 'Your MoEngage Data Center (DC). Can be 1, 2, 3, etc.'
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
security:
  - basicAuth: []
    moeAppKey: []

paths:
  /live-activity/broadcast/start:
    post:
      tags:
        - Live Activities
      summary: Start Broadcast Live Activity
      description: Initiates a shared, real-time activity for a large audience, such as a live sporting match or real-time election result tracking.
      requestBody:
        required: true
        description: The configuration for starting the Live Activity, including the initial content and alert message.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartLiveActivityRequest'
      responses:
        '200':
          description: Request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /live-activity/broadcast/update:
    post:
      tags:
        - Live Activities
      summary: Update Broadcast Live Activity
      description: Pushes a single, unified update to all subscribed Live Activities, such as an updated game score or a new development in a breaking news story.
      parameters:
        - name: X-Broadcast-Live-Activity-Id
          in: header
          required: true
          description: The unique identifier for the broadcast Live Activity campaign being updated.
          schema:
            type: string
      requestBody:
        required: true
        description: The payload containing the updated content state and optional alert for the Live Activity.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLiveActivityRequest'
      responses:
        '200':
          description: Request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /live-activity/broadcast/end:
    post:
      tags:
        - Live Activities
      summary: End Broadcast Live Activity
      description: Simultaneously terminates a broadcast Live Activity across all subscribed devices, with options for a final state update or immediate dismissal.
      parameters:
        - name: X-Broadcast-Live-Activity-Id
          in: header
          required: true
          description: The unique identifier for the broadcast Live Activity campaign being ended.
          schema:
            type: string
      requestBody:
        required: true
        description: The payload containing the final content state and dismissal information for the Live Activity.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndLiveActivityRequest'
      responses:
        '200':
          description: Request was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic Authentication using Workspace ID as username and Push API Key as password.
    moeAppKey:
      type: apiKey
      in: header
      name: X-MOE-APPKEY
      description: Your MoEngage Workspace ID.

  schemas:
    ErrorDetail:
      type: object
      properties:
        code: { type: string, example: "extra_forbidden" }
        target: { type: string, example: "ios.alert.metrics" }
        message: { type: string, example: "Extra inputs are not permitted" }

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: "PayloadError"
            message:
              type: string
              example: "Mandatory fields are missing or invalid"
            details:
              type: array
              items:
                $ref: '#/components/schemas/ErrorDetail'
    
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            instance_id:
              type: string
              example: "1749822841120-57c5c617"
            message:
              type: string
              example: "success"

    AlertObject:
      type: object
      required: [title, body]
      properties:
        title:
          type: string
          description: The primary heading of the alert.
        subtitle:
          type: string
          description: Additional context for the alert.
        body:
          oneOf:
            - type: string
            - type: object
          description: The main message content of the alert.
        sound:
          type: string
          description: The name of a sound file in the app bundle, or "default".

    IOSStartPayload:
      type: object
      required: [attribute_type, attribute_info, content_state, alert]
      properties:
        dismissal_date:
          type: integer
          format: int64
          description: Epoch timestamp (seconds) for automatic dismissal.
        attribute_type:
          type: string
          description: The data model/struct name registered in your iOS app for the activity.
          example: "LiveActivityAttributes"
        attribute_info:
          type: object
          additionalProperties: true
          description: JSON object with values for the static attributes declared in `attribute_type`.
        content_state:
          type: object
          additionalProperties: true
          description: JSON object representing the initial dynamic state of the activity.
        alert:
          $ref: '#/components/schemas/AlertObject'

    IOSUpdatePayload:
      type: object
      required: [content_state, alert]
      properties:
        dismissal_date:
          type: integer
          format: int64
          description: Epoch timestamp (seconds) for automatic dismissal.
        stale_date:
          type: integer
          format: int64
          description: Epoch timestamp (seconds) at which the content is considered outdated.
        content_state:
          type: object
          additionalProperties: true
          description: JSON object representing the updated dynamic state of the activity.
        alert:
          $ref: '#/components/schemas/AlertObject'

    StartLiveActivityRequest:
      type: object
      required: [broadcast_live_activity_id, ios]
      properties:
        broadcast_live_activity_id:
          type: string
          description: The unique identifier for the broadcast Live Activity campaign.
        instance_id:
          type: string
          description: Optional unique identifier for this specific broadcast instance.
        ios:
          $ref: '#/components/schemas/IOSStartPayload'

    UpdateLiveActivityRequest:
      type: object
      required: [broadcast_live_activity_id, ios]
      properties:
        broadcast_live_activity_id:
          type: string
          description: The unique identifier for the broadcast Live Activity campaign.
        instance_id:
          type: string
          description: Optional unique identifier for this specific broadcast instance.
        ios:
          $ref: '#/components/schemas/IOSUpdatePayload'
          
    EndLiveActivityRequest:
      type: object
      required: [broadcast_live_activity_id, ios]
      properties:
        broadcast_live_activity_id:
          type: string
          description: The unique identifier for the broadcast Live Activity campaign.
        instance_id:
          type: string
          description: Optional unique identifier for this specific broadcast instance.
        ios:
          $ref: '#/components/schemas/IOSUpdatePayload'

  responses:
    BadRequest:
      description: Bad Request. The request body is malformed or missing required fields.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized. Authentication credentials are missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Forbidden. The feature might not be enabled for your account, or the operation is not allowed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TooManyRequests:
      description: Too Many Requests. You have exceeded the rate limit.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal Server Error. An unexpected error occurred on the server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'