openapi: 3.0.3
info:
  title: MoEngage On-Site Messaging (OSM) Template API
  version: '1.0'
  description: API for creating, updating, and searching On-Site Messaging (OSM) templates within the MoEngage platform.
tags:
  - name: OSM Templates
    description: Operations to manage On-Site Messaging (OSM) templates.
servers:
  - url: 'https://api-0{dc}.moengage.com/v1.0'
    description: MoEngage Custom Templates API Server
    variables:
      dc:
        default: '1'
        description: 'Your MoEngage Data Center (DC). Can be 1, 2, 3, etc.'
        enum:
          - '1'
          - '2'
          - '3'
          - '4'
security:
  - basicAuth: []

paths:
  /custom-templates/osm:
    post:
      tags:
        - OSM Templates
      summary: Create OSM Template
      description: Creates a new On-Site Messaging (OSM) template. This API helps you upload templates created outside the MoEngage ecosystem to MoEngage and use them for campaign creation.
      requestBody:
        required: true
        description: The details of the OSM template to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOsmTemplateRequest'
            example:
              basic_details:
                payload: "<html><body><h1>Your HTML Content Here</h1></body></html>"
                template_type": "BANNER"
              meta_info:
                created_by": "testuser@moengage.com"
                template_id": "123123123"
                template_name": "Test"
                template_version": "1"
      responses:
        '200':
          description: Template created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  external_template_id:
                    type: string
                    format: uuid
                    description: The unique ID assigned to the newly created template by MoEngage.
                    example: "d05a44f0-a7cf-471a-bcb6-63054800a367"
        '400':
          description: Bad Request. The request is invalid due to missing fields, duplicate `template_id` and `template_version`, or other validation errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication Failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit breached (100 RPM) or template quota exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - OSM Templates
      summary: Update OSM Template
      description: Updates an existing On-Site Messaging (OSM) template by specifying its `external_template_id`.
      requestBody:
        required: true
        description: The updated details for the OSM template.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOsmTemplateRequest'
            example:
              external_template_id: "81e1a740-3e57-4c70-8ec7-ffc84d576498"
              update_campaigns: false
              basic_details:
                payload: "<html><body><h1>Updated HTML Content</h1></body></html>"
              meta_info:
                template_name: "AD template updated API 1"
                template_id": "133434477456"
                template_version": "2"
                updated_by": "testuser@moengage.com"
      responses:
        '200':
          description: Template updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  external_template_id:
                    type: string
                    format: uuid
                    description: The unique ID of the updated template.
                    example: "4a1afbc5-4c31-4f19-8c23-793e27af01aa"
        '400':
          description: Bad Request. Invalid `external_template_id` or other request data validation errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /custom-templates/osm/search:
    post:
      tags:
        - OSM Templates
      summary: Search OSM Templates
      description: Searches and retrieves a list of On-Site Messaging (OSM) templates based on specified filter criteria.
      requestBody:
        required: true
        description: Search filters for finding OSM templates. An empty body will fetch all templates. Pagination is mandatory after November 15, 2025.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchOsmTemplateRequest'
            example:
              page: 1
              entries: 10
              template_source": ["API"]
              sort_params":
                - last_modified_date: "DESCENDING"
      responses:
        '200':
          description: Search successful. Returns a list of templates.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchOsmTemplateResponse'
        '400':
          description: Bad Request. Invalid field values in the search criteria.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit breached (100 RPM).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic Authentication using Workspace ID as username and the 'Campaign report/Business events/Custom templates' API key as the password.

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: "400 Bad Request"
            message:
              type: string
              example: "Duplicate - template_id and template_version"
            details:
              type: array
              items:
                type: object
                properties:
                  code: { type: string, example: "InvalidValue" }
                  target: { type: string, example: "Duplicate - template_id and template_version" }
                  message: { type: string, example: "template_id:BasicTemplate1 template_version:1 is already present." }
            request_id:
              type: string
              example: "cLCcgLQj"
        title:
          type: string
          description: An alternative error title format.
          example: "Authentication required"
        description:
          type: string
          description: An alternative error description format.
          example: "MOE-APPKEY missing in Authentication Header"

    CreateOsmTemplateRequest:
      type: object
      required:
        - basic_details
        - meta_info
      properties:
        basic_details:
          type: object
          required:
            - payload
            - template_type
          properties:
            payload:
              type: string
              description: HTML content for the template.
            template_type:
              type: string
              enum: [BANNER, POP_UP, NUDGE]
        meta_info:
          type: object
          required:
            - created_by
            - template_id
            - template_name
            - template_version
          properties:
            created_by:
              type: string
              description: Identifier for the creator of the template.
            template_id:
              type: string
              description: A unique ID for the template provided by you.
            template_name:
              type: string
              description: The name of the template.
            template_version:
              type: string
              description: The version of the template.

    UpdateOsmTemplateRequest:
      type: object
      required:
        - external_template_id
        - basic_details
        - meta_info
      properties:
        external_template_id:
          type: string
          format: uuid
          description: The unique ID generated by MoEngage during template creation.
        update_campaigns:
          type: boolean
          default: false
          description: If true, updates all active campaigns using this template to the new version.
        basic_details:
          type: object
          required:
            - payload
          properties:
            payload:
              type: string
              description: The updated HTML content.
        meta_info:
          type: object
          required:
            - template_name
            - template_id
            - updated_by
          properties:
            template_name:
              type: string
              description: The name of the template being updated.
            template_id:
              type: string
              description: A unique ID for the template provided by you.
            template_version:
              type: string
              description: Optional new version for the template.
            updated_by:
              type: string
              format: email
              description: The email ID of the person updating the template.

    SearchOsmTemplateRequest:
      type: object
      description: All fields are optional. An empty request body will fetch all templates.
      properties:
        page:
          type: integer
          description: The page number of the results to fetch. Mandatory after Nov 15, 2025.
        entries:
          type: integer
          description: The number of templates to return per page. Max 15. Mandatory after Nov 15, 2025.
          maximum: 15
        template_name:
          type: string
          description: The name of the template to search for (partial search supported).
        template_id:
          type: string
          description: The ID of the template.
        template_source:
          type: array
          items:
            type: string
            enum: [API, MOENGAGE]
        template_type:
          type: array
          items:
            type: string
            enum: [CUSTOM, PRE_BUILT]
        created_by:
          type: array
          items:
            type: string
            format: email
        updated_by:
          type: array
          items:
            type: string
            format: email
        sort_params:
          type: array
          items:
            type: object
            properties:
              template_name:
                type: string
                enum: [ASCENDING, DESCENDING]
              last_modified_date:
                type: string
                enum: [ASCENDING, DESCENDING]
              last_modified_by:
                type: string
                enum: [ASCENDING, DESCENDING]
        template_ids:
          type: array
          items:
            type: object
            properties:
              external_template_id:
                type: string
                format: uuid
              version:
                type: integer

    OsmTemplate:
      type: object
      properties:
        external_template_id:
          type: string
          format: uuid
        version:
          type: integer
        basic_details:
          type: object
          properties:
            payload:
              type: string
            preview_image:
              type: string
              format: uri
        meta_info:
          type: object
          properties:
            template_id: { type: string }
            template_name: { type: string }
            template_version: { type: string }
            created_by: { type: string }
            channel: { type: string, example: "ON-SITE" }
            template_source: { type: string, enum: [API, MOENGAGE] }
            template_type: { type: string, enum: [CUSTOM, PRE_BUILT] }
        created_by:
          type: string
        created_at:
          type: string
          format: date-time
        updated_by:
          type: string
        updated_at:
          type: string
          format: date-time

    SearchOsmTemplateResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OsmTemplate'